language: python
sudo: required
services: docker

branches:
  only:
    - master

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-4.9

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99
  - pip install matplotlib numpy tabulate pyyaml tensorflow
  - sudo chmod +x src/fillp.py

env:
    matrix:
      - CMD='test/setup.py --schemes quic --install-deps &&
        test/setup.py --schemes quic --setup &&
        test/test.py local --schemes quic -t 10'
      - CMD='SCHEMES="default_tcp vegas bbr ledbat pcc verus sprout webrtc
        scream copa taova koho_cc calibrated_koho indigo fillp" &&
        test/setup.py --schemes "$SCHEMES" --install-deps &&
        test/setup.py --schemes "$SCHEMES" --setup &&
        src/tests/test_schemes.py &&
        test/tests/local_test.py &&
        analysis/tests/test_analyze.py'

script:
  - ./install_deps.sh && eval $CMD

notifications:
    email: false
